version: "2.0"

volumes:
  mongo-data:

services:
  mongo:
    image: mongo:7.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password